# Use the Drupal Association’s maintained CI templates.
# They install core for you, build a test site, merge your module’s composer.json,
# and run composer lint, phpcs, phpstan, and phpunit with sane defaults.
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

# Optional: speed up the pipeline for a backend‑only module by skipping front‑end linters and Nightwatch.
variables:
  SKIP_ESLINT: "1"
  SKIP_STYLELINT: "1"
  SKIP_NIGHTWATCH: "1"
# Optional: broaden test matrix (uncomment if you want them).
#  OPT_IN_TEST_PREVIOUS_MINOR: '1'
#  OPT_IN_TEST_NEXT_MINOR: '1'
#  OPT_IN_TEST_NEXT_MAJOR: '1'
